### ISSUE TITLE
Cakephp version ?

### ISSUE THREAD

**Issue by Quentinvarquet** [QoboLtd/cakephp-forums#11]
Hello,

I am trying to find a way to add a forum on my cakephp 3 website. Is your version working ? Is-it working with cakephp 3 ?

Thank you !

**Comment by mamchenkov** [comment]
Hi @Quentinvarquet ,

the plugin was initially developed for CakePHP v3, but it was a very quick and rough implementation and we haven't touched it in a long long while.  We will probably update it at some point this year (or early next), but for now it's not something that we officially support.

If it works for you - great.  If not - be warned! :smile:
